@patch('resource_management.libraries.script.Script.put_structured_out')
def test_rebalance_hdfs(self, pso):
    Popen_Mock.return_value = 1
    with patch('subprocess.Popen', new_callable=Popen_Mock):
        ll = subprocess.Popen()
        self.assertTrue(isinstance(ll.stdout.readline(), str))
        try:
            self.executeScript('2.0.6/services/HDFS/package/scripts/namenode.py', classname='NameNode', command='rebalancehdfs', config_file='rebalancehdfs_default.json')
            self.fail('Exception was not thrown')
        except resource_management.core.exceptions.Fail:
            pass
        pso.reset_mock()
        Popen_Mock.return_value = 0
        ll = subprocess.Popen()
        self.assertTrue(isinstance(ll.stdout.readline(), str))
        self.executeScript('2.0.6/services/HDFS/package/scripts/namenode.py', classname='NameNode', command='rebalancehdfs', config_file='rebalancehdfs_default.json')
        self.assertEqual(pso.call_count, 2, 'Output was not parsed properly')
