@patch('resource_management.libraries.script.Script.put_structured_out')
def test_rebalance_hdfs(self, pso):
    Popen_Mock.return_value = 1
    with patch('subprocess.Popen', new_callable=Popen_Mock):
        ll = subprocess.Popen()
        self.assertTrue(isinstance(ll.stdout.readline(), str))
        try:
            self.executeScript((self.COMMON_SERVICES_PACKAGE_DIR + '/scripts/namenode.py'), classname='NameNode', command='rebalancehdfs', config_file='rebalancehdfs_default.json', hdp_stack_version=self.STACK_VERSION, target=RMFTestCase.TARGET_COMMON_SERVICES)
            self.fail('Exception was not thrown')
        except resource_management.core.exceptions.Fail:
            pass
        pso.reset_mock()
        Popen_Mock.return_value = 0
        ll = subprocess.Popen()
        self.assertTrue(isinstance(ll.stdout.readline(), str))
        self.executeScript((self.COMMON_SERVICES_PACKAGE_DIR + '/scripts/namenode.py'), classname='NameNode', command='rebalancehdfs', config_file='rebalancehdfs_default.json', hdp_stack_version=self.STACK_VERSION, target=RMFTestCase.TARGET_COMMON_SERVICES)
        self.assertEqual(pso.call_count, 2, 'Output was not parsed properly')
