def test_exceptions(self):
    self.assertRaises(ValueError, StatusCheck, 'tmp', 'tmp')
