def is_repo_error_output(self, out):
    return ('Failure when receiving data from the peer' in out)
