def assert_traceback_matches(self, callback, expected_tb):
    try:
        callback()
    except Exception as e:
        tb = format_exception(*sys.exc_info())
        if (re.search(expected_tb.strip(), ''.join(tb)) is None):
            raise self.fail(('Traceback did not match:\n\n%s\nexpected:\n%s' % (''.join(tb), expected_tb)))
    else:
        self.fail('Expected exception')
