{
  try {
    init();
    monitor();
    waitOnAllDaemonThreads();
  }
 catch (  Throwable t) {
    LOG.fatal("Caught exception in main.",t);
    System.exit(1);
  }
}
