from resource_management.core.exceptions import Fail
