import logging
import subprocess
from exceptions import Fail
log = logging.getLogger('resource_management.provider')
