@wrap_exceptions
def resume(self):
    return cext.proc_resume(self.pid)
