@patch('os.walk')
@patch('zipfile.ZipFile')
@patch.object(BackupRestore, 'zipdir')
def test_perform_backup(self, zipdir_mock, zipfile_mock, oswalk_mock):
    files_mock = MagicMock()
    files_mock.__iter__.return_value = ['file1', 'file2']
    path_mock = MagicMock()
    zipname_mock = MagicMock()
    bkRestore = BackupRestore.BackupRestore(files_mock, zipname_mock, path_mock)
    bkRestore.perform_backup()
    self.assertEqual(zipfile_mock.call_count, 1)
    self.assertEqual(zipdir_mock.call_count, 1)
    zipfile_mock.side_effect = Exception('Invalid path!')
    try:
        bkRestore.perform_backup()
        self.fail('should throw exception')
    except:
        self.assertTrue(True)
